version: "3.8"

x-rds-url: &rds-host "travelhub-db.cipyouuaqkqn.us-east-1.rds.amazonaws.com"
x-rds-user: &rds-user "postgres"
x-rds-pass: &rds-pass "ogvynJXnQk7zLG4K"
x-jwt-secret: &jwt-secret "tu-clave-jwt-secreta-debe-ser-mas-larga-y-compleja-en-produccion-2026"

services:
  auth-service:
    build: ./auth-service
    ports:
      - "5010:5000"
    environment:
      AUTH_DATABASE_URL: postgresql://postgres:ogvynJXnQk7zLG4K@travelhub-db.cipyouuaqkqn.us-east-1.rds.amazonaws.com:5432/postgres
      JWT_SECRET: tu-clave-jwt-secreta-debe-ser-mas-larga-y-compleja-en-produccion-2026
      CATALOG_SERVICE_URL: http://catalog-service:5001
    networks:
      - travelhub-net

  catalog-service:
    build: ./catalog-service
    ports:
      - "5001:5001"
    environment:
      CATALOG_DATABASE_URL: postgresql://postgres:ogvynJXnQk7zLG4K@travelhub-db.cipyouuaqkqn.us-east-1.rds.amazonaws.com:5432/postgres
      CACHE_TTL: 300
      S3_BUCKET: travelhub-images-proyecto
      S3_REGION: us-east-1
    networks:
      - travelhub-net

  client-gateway:
    build: ./client-gateway
    ports:
      - "8000:8000"
    environment:
      AUTH_SERVICE_URL: http://auth-service:5000
      CATALOG_SERVICE_URL: http://catalog-service:5001
      RESERVATION_SERVICE_URL: http://reservation-service:5002
      JWT_SECRET: tu-clave-jwt-secreta-debe-ser-mas-larga-y-compleja-en-produccion-2026
    depends_on:
      - auth-service
      - catalog-service
      - reservation-service
    networks:
      - travelhub-net

  reservation-service:
    build: ./reservation-service
    ports:
      - "5002:5002"
    environment:
      RESERVATION_DATABASE_URL: postgresql://postgres:ogvynJXnQk7zLG4K@travelhub-db.cipyouuaqkqn.us-east-1.rds.amazonaws.com:5432/postgres
      JWT_SECRET: tu-clave-jwt-secreta-debe-ser-mas-larga-y-compleja-en-produccion-2026
    networks:
      - travelhub-net

networks:
  travelhub-net:
    driver: bridge
